import '../styles/globals.scss';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Header from '../components/Header';
import { useRouter } from 'next/router';
import { AnimatePresence } from 'framer-motion';



export default function App({ Component, pageProps }: AppProps) {
  const { route } = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <meta name="theme-color" content="#303030" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <AnimatePresence mode='wait'>
          <Component {...pageProps} key={route} />
        </AnimatePresence>
        <footer className='footer'>x</footer>
      </>
    </>
  );
}
