name: Deploy to S3

on:
  pull_request:
    branches: [ main-origin ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./App/misterpea.me
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm ci
      - run: npm run export

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2
      - run: aws s3 sync ./out s3://misterpea.me
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PORTFOLIO_DISTRIBUTION_ID }} --paths /index.html

      
